### ISSUE TITLE
IMG's width

### ISSUE THREAD

**Issue by cardangi** [tkovs/mixmaster-mixes#5]
As imagens estão com tamanhos diferenciados, deixando totalmente desalinhado/torto, estragando a row/grid's.

Enquanto a primeira tem 38 x 77, a quarta tem 140 x 164, não há alinhamento que fique bonito desse jeito.

sugestão:

img {
width: 100px;
height: 100px;
}

**Comment by tkovs** [comment]
Já foi consertado.
